import { Router } from "express";
import { z } from "zod";
import pool from "../config/database_connection";
import { verifyAdminToken, verifyPlayerToken, type AuthenticatedRequest } from "../middlewares/authentication_middleware";
import { logActivity } from "../helpers/activityLog";
import { backfillBadgeAwards } from "../services/badge_service";

const router=Router(),uuid=z.string().uuid();
const schema=z.object({name:z.string().trim().min(2).max(120),description:z.string().trim().max(500).default(""),tier:z.enum(["bronze","silver","gold","platinum"]),criteriaType:z.enum(["levels_completed","attempts_completed","perfect_scores","total_xp"]),criteriaValue:z.number().int().positive().max(10000000),isActive:z.boolean().default(true),sortOrder:z.number().int().min(0).max(10000).default(0)});
const invalid=(res:any,error:any)=>res.status(400).json({success:false,errors:error.issues});

router.get("/admin/badges",verifyAdminToken,async(_req,res)=>{const r=await pool.query(`SELECT b.*,COUNT(ub.user_id)::int earned_count FROM badges b LEFT JOIN user_badges ub ON ub.badge_id=b.id GROUP BY b.id ORDER BY b.sort_order,b.name`);res.json({success:true,badges:r.rows});});
router.post("/admin/badges",verifyAdminToken,async(req,res)=>{const v=schema.safeParse(req.body);if(!v.success)return invalid(res,v.error);const d=v.data;try{const r=await pool.query(`INSERT INTO badges(name,description,tier,criteria_type,criteria_value,is_active,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[d.name,d.description,d.tier,d.criteriaType,d.criteriaValue,d.isActive,d.sortOrder]);await backfillBadgeAwards(r.rows[0].id);await logActivity({eventType:"badges.created",title:"Badge created",description:`${d.name} was created`});res.status(201).json({success:true,badge:r.rows[0]});}catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"A badge with this name already exists.":"Badge could not be created."});}});
router.put("/admin/badges/:id",verifyAdminToken,async(req,res)=>{if(!uuid.safeParse(req.params.id).success)return res.status(400).json({success:false,message:"Invalid badge."});const v=schema.safeParse(req.body);if(!v.success)return invalid(res,v.error);const d=v.data;try{const r=await pool.query(`UPDATE badges SET name=$1,description=$2,tier=$3,criteria_type=$4,criteria_value=$5,is_active=$6,sort_order=$7,updated_at=NOW() WHERE id=$8 RETURNING *`,[d.name,d.description,d.tier,d.criteriaType,d.criteriaValue,d.isActive,d.sortOrder,req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Badge not found."});await backfillBadgeAwards(r.rows[0].id);await logActivity({eventType:"badges.updated",title:"Badge updated",description:`${d.name} was updated`});res.json({success:true,badge:r.rows[0]});}catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"A badge with this name already exists.":"Badge could not be updated."});}});
router.delete("/admin/badges/:id",verifyAdminToken,async(req,res)=>{if(!uuid.safeParse(req.params.id).success)return res.status(400).json({success:false,message:"Invalid badge."});const r=await pool.query("DELETE FROM badges WHERE id=$1 RETURNING name",[req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Badge not found."});await logActivity({eventType:"badges.deleted",title:"Badge deleted",description:`${r.rows[0].name} was deleted`});res.json({success:true,message:"Badge deleted."});});
router.get("/badges/me",verifyPlayerToken,async(req:AuthenticatedRequest,res)=>{const r=await pool.query(`SELECT b.*,ub.earned_at,(ub.user_id IS NOT NULL) earned FROM badges b LEFT JOIN user_badges ub ON ub.badge_id=b.id AND ub.user_id=$1 WHERE b.is_active=true ORDER BY b.sort_order,b.name`,[req.user!.id]);res.json({success:true,badges:r.rows});});
export default router;
