import { Router } from "express";
import { z } from "zod";
import pool from "../config/database_connection";
import { verifyAdminToken, type AuthenticatedRequest } from "../middlewares/authentication_middleware";
import { logActivity } from "../helpers/activityLog";

const router = Router();
router.use(verifyAdminToken);
const uuid = z.string().uuid();
const ageSchema = z.object({ name:z.string().trim().min(2).max(120), minAge:z.number().int().min(1).max(130), maxAge:z.number().int().min(1).max(130), subtitle:z.string().trim().max(180).default(""), description:z.string().trim().max(2000).default(""), imageUrl:z.string().url().or(z.literal("")).optional() }).refine(v=>v.maxAge>=v.minAge,{message:"Maximum age must be greater than or equal to minimum age."});
const categorySchema = z.object({ ageGroupId:uuid, name:z.string().trim().min(2).max(120), description:z.string().trim().max(2000).default(""), imageUrl:z.string().url().or(z.literal("")).optional() });
const levelSchema = z.object({ categoryId:uuid, name:z.string().trim().min(1).max(120), levelNumber:z.number().int().min(1), description:z.string().trim().max(2000).default(""), imageUrl:z.string().url().or(z.literal("")).optional(), pointsPerQuestion:z.number().int().min(1).max(1000).default(10), timeLimitSeconds:z.number().int().min(5).max(600).default(30) });
const invalid = (res:any, issues:any) => res.status(400).json({success:false,errors:issues});

router.get("/age-groups", async (_req,res) => { const r=await pool.query(`SELECT a.*,COUNT(DISTINCT c.id)::int category_count,COUNT(DISTINCT l.id)::int level_count FROM age_groups a LEFT JOIN game_categories c ON c.age_group_id=a.id LEFT JOIN game_levels l ON l.category_id=c.id GROUP BY a.id ORDER BY a.min_age`); res.json({success:true,ageGroups:r.rows}); });
router.post("/age-groups", async (req:AuthenticatedRequest,res) => { const v=ageSchema.safeParse(req.body); if(!v.success)return invalid(res,v.error.issues); const d=v.data; try { const r=await pool.query(`INSERT INTO age_groups(name,min_age,max_age,subtitle,description,image_url) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[d.name,d.minAge,d.maxAge,d.subtitle,d.description,d.imageUrl||null]); await logActivity({eventType:"catalog.age_group_created",title:"Age group created",description:`${d.name} was created`,metadata:{id:r.rows[0].id}}); res.status(201).json({success:true,ageGroup:r.rows[0]}); } catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"That age range already exists.":"Age group could not be created."});} });
router.put("/age-groups/:id", async (req,res) => { if(!uuid.safeParse(req.params.id).success)return invalid(res,[{message:"Invalid age group."}]); const v=ageSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;const r=await pool.query(`UPDATE age_groups SET name=$1,min_age=$2,max_age=$3,subtitle=$4,description=$5,image_url=$6,updated_at=NOW() WHERE id=$7 RETURNING *`,[d.name,d.minAge,d.maxAge,d.subtitle,d.description,d.imageUrl||null,req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Age group not found."});await logActivity({eventType:"catalog.age_group_updated",title:"Age group updated",description:`${d.name} was updated`});res.json({success:true,ageGroup:r.rows[0]}); });
router.delete("/age-groups/:id", async (req,res) => { if(!uuid.safeParse(req.params.id).success)return invalid(res,[{message:"Invalid age group."}]);const r=await pool.query("DELETE FROM age_groups WHERE id=$1 RETURNING name",[req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Age group not found."});await logActivity({eventType:"catalog.age_group_deleted",title:"Age group deleted",description:`${r.rows[0].name} and its contents were deleted`});res.json({success:true,message:"Age group deleted."}); });

router.get("/age-groups/:id/categories", async (req,res) => { const r=await pool.query(`SELECT c.*,COUNT(l.id)::int level_count FROM game_categories c LEFT JOIN game_levels l ON l.category_id=c.id WHERE c.age_group_id=$1 GROUP BY c.id ORDER BY c.created_at`,[req.params.id]);res.json({success:true,categories:r.rows}); });
router.post("/categories", async (req,res) => { const v=categorySchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;try{const r=await pool.query(`INSERT INTO game_categories(age_group_id,name,description,image_url) VALUES($1,$2,$3,$4) RETURNING *`,[d.ageGroupId,d.name,d.description,d.imageUrl||null]);await logActivity({eventType:"catalog.category_created",title:"Category created",description:`${d.name} was created`});res.status(201).json({success:true,category:r.rows[0]});}catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"This category already exists in the age group.":"Category could not be created."});} });
router.put("/categories/:id", async (req,res) => { const v=categorySchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;const r=await pool.query(`UPDATE game_categories SET age_group_id=$1,name=$2,description=$3,image_url=$4,updated_at=NOW() WHERE id=$5 RETURNING *`,[d.ageGroupId,d.name,d.description,d.imageUrl||null,req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Category not found."});await logActivity({eventType:"catalog.category_updated",title:"Category updated",description:`${d.name} was updated`});res.json({success:true,category:r.rows[0]}); });
router.delete("/categories/:id", async (req,res) => { const r=await pool.query("DELETE FROM game_categories WHERE id=$1 RETURNING name",[req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Category not found."});await logActivity({eventType:"catalog.category_deleted",title:"Category deleted",description:`${r.rows[0].name} and its levels were deleted`});res.json({success:true,message:"Category deleted."}); });

router.get("/categories/:id/levels", async (req,res) => { const r=await pool.query("SELECT * FROM game_levels WHERE category_id=$1 ORDER BY level_number",[req.params.id]);res.json({success:true,levels:r.rows}); });
router.post("/levels", async (req,res) => { const v=levelSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;try{const r=await pool.query(`INSERT INTO game_levels(category_id,name,level_number,description,image_url,points_per_question,time_limit_seconds) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[d.categoryId,d.name,d.levelNumber,d.description,d.imageUrl||null,d.pointsPerQuestion,d.timeLimitSeconds]);await logActivity({eventType:"catalog.level_created",title:"Level created",description:`${d.name} was created`});res.status(201).json({success:true,level:r.rows[0]});}catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"That level number already exists.":"Level could not be created."});} });
router.put("/levels/:id", async (req,res) => { const v=levelSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;const r=await pool.query(`UPDATE game_levels SET category_id=$1,name=$2,level_number=$3,description=$4,image_url=$5,points_per_question=$6,time_limit_seconds=$7,updated_at=NOW() WHERE id=$8 RETURNING *`,[d.categoryId,d.name,d.levelNumber,d.description,d.imageUrl||null,d.pointsPerQuestion,d.timeLimitSeconds,req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Level not found."});await logActivity({eventType:"catalog.level_updated",title:"Level updated",description:`${d.name} was updated`});res.json({success:true,level:r.rows[0]}); });
router.delete("/levels/:id", async (req,res) => { const r=await pool.query("DELETE FROM game_levels WHERE id=$1 RETURNING name",[req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Level not found."});await logActivity({eventType:"catalog.level_deleted",title:"Level deleted",description:`${r.rows[0].name} was deleted`});res.json({success:true,message:"Level deleted."}); });

export default router;
