import { Router } from "express";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import pool from "../config/database_connection";
import { verifyPlayerToken, type AuthenticatedRequest } from "../middlewares/authentication_middleware";
import { recordCoinTransaction } from "../services/coin_service";

const router=Router();
const attemptSchema=z.object({attemptId:z.string().uuid(),levelId:z.string().uuid(),answers:z.array(z.object({questionId:z.string().uuid(),optionId:z.string().uuid()})).max(500)});
const actionSchema=z.object({actionId:z.string().uuid(),eventKey:z.enum(["question_skipped","wrong_option_removed","answer_revealed"]),levelId:z.string().uuid(),questionId:z.string().uuid()});
const answerCheckSchema=z.object({levelId:z.string().uuid(),questionId:z.string().uuid(),optionId:z.string().uuid()});
router.use(["/gameplay/refill","/gameplay/attempts"],verifyPlayerToken);
router.use(["/gameplay/actions"],verifyPlayerToken);

router.get("/gameplay/status",verifyPlayerToken,async(req:AuthenticatedRequest,res)=>{const r=await pool.query(`SELECT u.coins_count,u.lives_remaining,s.max_lives,s.passing_score_percent,s.refill_coin_cost FROM users u CROSS JOIN gameplay_settings s WHERE u.id=$1 AND s.id=1`,[req.user!.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Player not found."});res.json({success:true,...r.rows[0]});});

router.get("/gameplay/categories/:categoryId/levels",verifyPlayerToken,async(req:AuthenticatedRequest,res)=>{if(!z.string().uuid().safeParse(req.params.categoryId).success)return res.status(400).json({success:false,message:"Invalid category."});const r=await pool.query(`SELECT l.id,l.name,l.level_number,l.description,l.image_url,l.points_per_question,l.time_limit_seconds,COALESCE(MAX(a.score_percent),0)::int best_score,COALESCE(BOOL_OR(a.passed),false) completed FROM game_levels l LEFT JOIN gameplay_attempts a ON a.level_id=l.id AND a.user_id=$1 WHERE l.category_id=$2 GROUP BY l.id ORDER BY l.level_number`,[req.user!.id,req.params.categoryId]);const rows=r.rows as Array<Record<string,any>>;const levels=rows.map((level:Record<string,any>,index:number,all:Array<Record<string,any>>)=>({...level,unlocked:index===0||Boolean(all[index-1]?.completed)}));res.json({success:true,levels});});

router.post("/gameplay/check-answer",verifyPlayerToken,async(req,res)=>{const parsed=answerCheckSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,errors:parsed.error.issues});const d=parsed.data;const r=await pool.query(`SELECT o.is_correct,q.explanation FROM questions q JOIN question_options o ON o.question_id=q.id WHERE q.id=$1 AND q.level_id=$2 AND q.status='published' AND o.id=$3`,[d.questionId,d.levelId,d.optionId]);if(!r.rows[0])return res.status(404).json({success:false,message:"That answer option is not available for this question."});res.json({success:true,isCorrect:Boolean(r.rows[0].is_correct),explanation:r.rows[0].explanation||""});});

router.get("/gameplay/actions",async(_req,res)=>{const keys=["question_skipped","wrong_option_removed","answer_revealed"];const r=await pool.query("SELECT name,event_key,amount,description,is_active FROM coin_rules WHERE type='deduction' AND event_key=ANY($1) ORDER BY name",[keys]);res.json({success:true,actions:r.rows});});

router.post("/gameplay/actions",async(req:AuthenticatedRequest,res)=>{const parsed=actionSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,errors:parsed.error.issues});const d=parsed.data;const client=await pool.connect();try{await client.query("BEGIN");const ruleResult=await client.query("SELECT * FROM coin_rules WHERE event_key=$1 AND type='deduction' AND is_active=true",[d.eventKey]);const rule=ruleResult.rows[0];if(!rule){await client.query("ROLLBACK");return res.status(409).json({success:false,code:"RULE_INACTIVE",message:"This help option is not currently available."});}const options=await client.query(`SELECT o.id,o.is_correct FROM questions q JOIN question_options o ON o.question_id=q.id WHERE q.id=$1 AND q.level_id=$2 AND q.status='published' ORDER BY o.option_order`,[d.questionId,d.levelId]);if(!options.rowCount){await client.query("ROLLBACK");return res.status(404).json({success:false,message:"Question not found in this level."});}const tx=await recordCoinTransaction({userId:req.user!.id,type:"deduction",amount:Number(rule.amount),description:rule.description||rule.name,reference:`game-action:${d.actionId}`,ruleId:rule.id,metadata:{eventKey:d.eventKey,levelId:d.levelId,questionId:d.questionId}},client);let effect:Record<string,unknown>={};if(d.eventKey==="answer_revealed")effect={correctOptionId:options.rows.find((o:{is_correct:boolean})=>o.is_correct)?.id};if(d.eventKey==="wrong_option_removed"){const wrong=options.rows.filter((o:{is_correct:boolean})=>!o.is_correct);effect={removedOptionId:wrong[Math.floor(Math.random()*wrong.length)]?.id};}await client.query("COMMIT");res.status(201).json({success:true,eventKey:d.eventKey,amountDeducted:Number(rule.amount),coinBalance:Number(tx.balance_after),...effect});}catch(error:any){await client.query("ROLLBACK");if(error.code==="23505")return res.status(409).json({success:false,message:"This action was already processed."});if(error.status)return res.status(error.status).json({success:false,message:error.message});throw error;}finally{client.release();}});

router.post("/gameplay/refill",async(req:AuthenticatedRequest,res)=>{const client=await pool.connect();try{await client.query("BEGIN");const r=await client.query(`SELECT u.coins_count,u.lives_remaining,s.max_lives,s.refill_coin_cost FROM users u CROSS JOIN gameplay_settings s WHERE u.id=$1 AND s.id=1 FOR UPDATE OF u`,[req.user!.id]);const state=r.rows[0];if(!state){await client.query("ROLLBACK");return res.status(404).json({success:false,message:"Player not found."});}if(Number(state.lives_remaining)>0){await client.query("COMMIT");return res.json({success:true,refilled:false,livesRemaining:Number(state.lives_remaining),maxLives:Number(state.max_lives),coinBalance:Number(state.coins_count)});}if(Number(state.coins_count)<Number(state.refill_coin_cost)){await client.query("ROLLBACK");return res.status(409).json({success:false,code:"INSUFFICIENT_COINS",message:"You need more coins to restore your lives.",refillCoinCost:Number(state.refill_coin_cost),coinBalance:Number(state.coins_count)});}const tx=await recordCoinTransaction({userId:req.user!.id,type:"deduction",amount:Number(state.refill_coin_cost),description:`Refilled all ${state.max_lives} lives`,reference:`life-refill:manual:${randomUUID()}`},client);await client.query("UPDATE users SET lives_remaining=$1,updated_at=NOW() WHERE id=$2",[state.max_lives,req.user!.id]);await client.query("COMMIT");res.json({success:true,refilled:true,livesRemaining:Number(state.max_lives),maxLives:Number(state.max_lives),coinBalance:Number(tx.balance_after),refillCoinCost:Number(state.refill_coin_cost)});}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}});

router.post("/gameplay/attempts",async(req:AuthenticatedRequest,res)=>{const parsed=attemptSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,errors:parsed.error.issues});const d=parsed.data;const client=await pool.connect();try{await client.query("BEGIN");const duplicate=await client.query("SELECT result FROM gameplay_attempts WHERE id=$1 AND user_id=$2",[d.attemptId,req.user!.id]);if(duplicate.rows[0]){await client.query("COMMIT");return res.json({success:true,...duplicate.rows[0].result,replayed:true});}
 const settingsResult=await client.query("SELECT * FROM gameplay_settings WHERE id=1");const userResult=await client.query("SELECT coins_count,lives_remaining,total_xp FROM users WHERE id=$1 FOR UPDATE",[req.user!.id]);const questionResult=await client.query(`SELECT q.id question_id,o.id option_id FROM questions q JOIN question_options o ON o.question_id=q.id AND o.is_correct=true WHERE q.level_id=$1 AND q.status='published' ORDER BY q.id`,[d.levelId]);const levelResult=await client.query("SELECT points_per_question FROM game_levels WHERE id=$1",[d.levelId]);const bestResult=await client.query("SELECT COALESCE(MAX(correct_answers),0)::int best FROM gameplay_attempts WHERE user_id=$1 AND level_id=$2",[req.user!.id,d.levelId]);const settings=settingsResult.rows[0],user=userResult.rows[0],questions=questionResult.rows;if(!user){await client.query("ROLLBACK");return res.status(404).json({success:false,message:"Player not found."});}if(!questions.length||!levelResult.rows[0]){await client.query("ROLLBACK");return res.status(409).json({success:false,message:"This level has no playable questions."});}if(Number(user.lives_remaining)<=0){await client.query("ROLLBACK");return res.status(409).json({success:false,code:"NO_LIVES",message:"You need more coins to restore your lives.",livesRemaining:0,coinBalance:Number(user.coins_count),refillCoinCost:Number(settings.refill_coin_cost)});}
 const answerMap=new Map(d.answers.map(a=>[a.questionId,a.optionId]));const correct=questions.reduce((n:number,q:{question_id:string;option_id:string})=>n+(answerMap.get(q.question_id)===q.option_id?1:0),0);const total=questions.length;const score=Math.round(correct*100/total);const passed=score>=Number(settings.passing_score_percent);let lives=Number(user.lives_remaining),balance=Number(user.coins_count),refilled=false,needsPurchase=false,refillTransactionId=null;if(!passed){lives=Math.max(0,lives-1);if(lives===0){const cost=Number(settings.refill_coin_cost);if(balance>=cost){const tx=await recordCoinTransaction({userId:req.user!.id,type:"deduction",amount:cost,description:`Automatic refill to ${settings.max_lives} lives after a failed level`,reference:`life-refill:${d.attemptId}`,metadata:{levelId:d.levelId,attemptId:d.attemptId}},client);refillTransactionId=tx.id;balance=Number(tx.balance_after);lives=Number(settings.max_lives);refilled=true;}else needsPurchase=true;}await client.query("UPDATE users SET lives_remaining=$1,updated_at=NOW() WHERE id=$2",[lives,req.user!.id]);}
 const xpEarned=Math.max(0,correct-Number(bestResult.rows[0].best))*Number(levelResult.rows[0].points_per_question);const totalXp=Number(user.total_xp)+xpEarned;if(xpEarned>0)await client.query("UPDATE users SET total_xp=$1,updated_at=NOW() WHERE id=$2",[totalXp,req.user!.id]);const result={attemptId:d.attemptId,scorePercent:score,correctAnswers:correct,totalQuestions:total,passed,passingScorePercent:Number(settings.passing_score_percent),lifeLost:!passed,livesRemaining:lives,maxLives:Number(settings.max_lives),coinBalance:balance,refilled,refillCoinCost:Number(settings.refill_coin_cost),needsPurchase,xpEarned,totalXp};await client.query(`INSERT INTO gameplay_attempts(id,user_id,level_id,score_percent,correct_answers,total_questions,passed,life_lost,lives_after,refill_transaction_id,xp_awarded,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[d.attemptId,req.user!.id,d.levelId,score,correct,total,passed,!passed,lives,refillTransactionId,xpEarned,result]);await client.query("COMMIT");res.status(201).json({success:true,...result});}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}});

export default router;
