import { Router } from "express";
import pool from "../config/database_connection";
import { verifyAdminToken, verifyPlayerToken, type AuthenticatedRequest } from "../middlewares/authentication_middleware";

const router=Router();
const pageInfo=(q:any)=>({page:Math.max(1,Number(q.page)||1),limit:Math.min(100,Math.max(5,Number(q.limit)||20))});
const periodSql=(period:string)=>period==="week"?"AND a.created_at >= NOW() - INTERVAL '7 days'":period==="month"?"AND a.created_at >= NOW() - INTERVAL '30 days'":"";
const boardCte=(period:string)=>`WITH performance AS (SELECT u.id,u.name,u.username,u.total_xp,u.coins_count,u.lives_remaining,u.created_at,COALESCE(SUM(a.xp_awarded) FILTER (WHERE true ${periodSql(period)}),0)::int period_xp,COUNT(a.id) FILTER (WHERE true ${periodSql(period)})::int attempts,COUNT(DISTINCT a.level_id) FILTER (WHERE a.passed ${periodSql(period)})::int completed_levels,COALESCE(ROUND(AVG(a.score_percent) FILTER (WHERE true ${periodSql(period)})),0)::int average_score,MAX(a.created_at) FILTER (WHERE true ${periodSql(period)}) last_played FROM users u LEFT JOIN gameplay_attempts a ON a.user_id=u.id WHERE u.role='user' AND u.is_verified=true GROUP BY u.id), ranked AS (SELECT *,RANK() OVER(ORDER BY ${period==="all"?"total_xp":"period_xp"} DESC,completed_levels DESC,average_score DESC,created_at ASC,id ASC)::int rank FROM performance WHERE ${period==="all"?"total_xp > 0 OR attempts > 0":"attempts > 0"})`;

router.get("/leaderboard",async(req,res)=>{const period=["all","week","month"].includes(String(req.query.period))?String(req.query.period):"all";const {page,limit}=pageInfo(req.query);const search=String(req.query.search||"").trim();const values:any[]=[];let where="";if(search){values.push(`%${search}%`);where=`WHERE name ILIKE $1 OR username ILIKE $1`;}const count=await pool.query(`${boardCte(period)} SELECT COUNT(*)::int total FROM ranked ${where}`,values);values.push(limit,(page-1)*limit);const rows=await pool.query(`${boardCte(period)} SELECT id,name,username,total_xp,period_xp,attempts,completed_levels,average_score,last_played,rank FROM ranked ${where} ORDER BY rank LIMIT $${values.length-1} OFFSET $${values.length}`,values);res.json({success:true,period,players:rows.rows,pagination:{page,limit,total:Number(count.rows[0].total)}});});
router.get("/leaderboard/me",verifyPlayerToken,async(req:AuthenticatedRequest,res)=>{const period=["all","week","month"].includes(String(req.query.period))?String(req.query.period):"all";const r=await pool.query(`${boardCte(period)} SELECT id,name,username,total_xp,period_xp,attempts,completed_levels,average_score,last_played,rank FROM ranked WHERE id=$1`,[req.user!.id]);res.json({success:true,player:r.rows[0]||null,period});});
router.get("/admin/leaderboard",verifyAdminToken,async(req,res)=>{const period=["all","week","month"].includes(String(req.query.period))?String(req.query.period):"all";const {page,limit}=pageInfo(req.query);const search=String(req.query.search||"").trim();const values:any[]=[];let where="";if(search){values.push(`%${search}%`);where=`WHERE name ILIKE $1 OR username ILIKE $1`;}const count=await pool.query(`${boardCte(period)} SELECT COUNT(*)::int total FROM ranked ${where}`,values);values.push(limit,(page-1)*limit);const rows=await pool.query(`${boardCte(period)} SELECT id,name,username,total_xp,period_xp,coins_count,lives_remaining,attempts,completed_levels,average_score,last_played,rank FROM ranked ${where} ORDER BY rank LIMIT $${values.length-1} OFFSET $${values.length}`,values);res.json({success:true,period,players:rows.rows,pagination:{page,limit,total:Number(count.rows[0].total)}});});
export default router;
