import { Router } from "express";
import { z } from "zod";
import pool from "../config/database_connection";
import { verifyAdminToken, verifyPlayerToken, type AuthenticatedRequest } from "../middlewares/authentication_middleware";
import { logActivity } from "../helpers/activityLog";

const router=Router(),uuid=z.string().uuid();
const createSchema=z.object({title:z.string().trim().min(3).max(160),message:z.string().trim().min(5).max(3000),type:z.enum(["announcement","achievement","reminder","system"]).default("announcement"),audience:z.enum(["all","verified","unverified"]).default("all")});
const pageInfo=(q:any)=>({page:Math.max(1,Number(q.page)||1),limit:Math.min(50,Math.max(1,Number(q.limit)||10))});
const audienceSql=`(n.audience='all' OR (n.audience='verified' AND u.is_verified=true) OR (n.audience='unverified' AND u.is_verified=false))`;

router.post("/admin/notifications",verifyAdminToken,async(req:AuthenticatedRequest,res)=>{const v=createSchema.safeParse(req.body);if(!v.success)return res.status(400).json({success:false,errors:v.error.issues});const d=v.data;const actorId=req.user!.id==="super-admin"?null:req.user!.id;const actorName=req.user!.id==="super-admin"?"Super Admin":null;const r=await pool.query(`INSERT INTO notifications(title,message,type,audience,created_by,created_by_name) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[d.title,d.message,d.type,d.audience,actorId,actorName]);await logActivity({eventType:"notifications.sent",title:"Player notification sent",description:`${d.title} was sent to ${d.audience} players`,actorId,actorName,metadata:{notificationId:r.rows[0].id,audience:d.audience}});res.status(201).json({success:true,message:"Notification sent successfully.",notification:r.rows[0]});});
router.get("/admin/notifications",verifyAdminToken,async(req,res)=>{const{page,limit}=pageInfo(req.query);const[count,rows]=await Promise.all([pool.query("SELECT COUNT(*)::int total FROM notifications"),pool.query("SELECT * FROM notifications ORDER BY published_at DESC LIMIT $1 OFFSET $2",[limit,(page-1)*limit])]);res.json({success:true,notifications:rows.rows,pagination:{page,limit,total:Number(count.rows[0].total)}});});

router.get("/notifications",verifyPlayerToken,async(req:AuthenticatedRequest,res)=>{const{page,limit}=pageInfo(req.query);const unreadOnly=String(req.query.unreadOnly||"false")==="true";const values:any[]=[req.user!.id],extra=unreadOnly?"AND nr.user_id IS NULL":"";const[count,rows,unread]=await Promise.all([
 pool.query(`SELECT COUNT(*)::int total FROM notifications n CROSS JOIN users u LEFT JOIN notification_reads nr ON nr.notification_id=n.id AND nr.user_id=u.id WHERE u.id=$1 AND n.published_at<=NOW() AND ${audienceSql} ${extra}`,values),
 pool.query(`SELECT n.id,n.title,n.message,n.type,n.published_at,n.created_by_name,(nr.user_id IS NOT NULL) is_read FROM notifications n CROSS JOIN users u LEFT JOIN notification_reads nr ON nr.notification_id=n.id AND nr.user_id=u.id WHERE u.id=$1 AND n.published_at<=NOW() AND ${audienceSql} ${extra} ORDER BY n.published_at DESC LIMIT $2 OFFSET $3`,[req.user!.id,limit,(page-1)*limit]),
 pool.query(`SELECT COUNT(*)::int total FROM notifications n CROSS JOIN users u LEFT JOIN notification_reads nr ON nr.notification_id=n.id AND nr.user_id=u.id WHERE u.id=$1 AND n.published_at<=NOW() AND ${audienceSql} AND nr.user_id IS NULL`,[req.user!.id]),
]);res.json({success:true,notifications:rows.rows,unreadCount:Number(unread.rows[0].total),pagination:{page,limit,total:Number(count.rows[0].total)}});});
router.patch("/notifications/read-all",verifyPlayerToken,async(req:AuthenticatedRequest,res)=>{await pool.query(`INSERT INTO notification_reads(notification_id,user_id) SELECT n.id,u.id FROM notifications n CROSS JOIN users u WHERE u.id=$1 AND n.published_at<=NOW() AND ${audienceSql} ON CONFLICT DO NOTHING`,[req.user!.id]);res.json({success:true,message:"All notifications marked as read."});});
router.patch("/notifications/:id/read",verifyPlayerToken,async(req:AuthenticatedRequest,res)=>{if(!uuid.safeParse(req.params.id).success)return res.status(400).json({success:false,message:"Invalid notification."});const r=await pool.query(`INSERT INTO notification_reads(notification_id,user_id) SELECT n.id,u.id FROM notifications n CROSS JOIN users u WHERE n.id=$1 AND u.id=$2 AND n.published_at<=NOW() AND ${audienceSql} ON CONFLICT DO NOTHING RETURNING notification_id`,[req.params.id,req.user!.id]);if(!r.rows[0]){const exists=await pool.query("SELECT 1 FROM notification_reads WHERE notification_id=$1 AND user_id=$2",[req.params.id,req.user!.id]);if(!exists.rows[0])return res.status(404).json({success:false,message:"Notification not found."});}res.json({success:true});});
export default router;
